Task:
  pl_module: COCO_EfficientDet


Trainer:
  max_epochs: 100
  accelerator: gpu
  accumulate_grad_batches: 4
  log_every_n_steps: 100
  precision: 16
  limit_train_batches: 1.0


Callbacks:

  LearningRateMonitor:
    logging_interval: step
  ModelCheckpoint:
    every_n_epochs: 1
    save_last: true
    verbose: true


Profiler:
  PyTorchProfiler:

