Trainer:
  max_epochs: 100
  accelerator: gpu
  accumulate_grad_batches: 4
  log_every_n_steps: 100


Callbacks:
  EarlyStopping:
    monitor: val_map
    patience: 100
    check_on_train_epoch_end: False

  LearningRateMonitor:
    logging_interval: step


Profiler:
  PyTorchProfiler:

