Task:
  pl_module: COCO_EfficientDet


Trainer:
  max_epochs: 100
  accelerator: gpu
  accumulate_grad_batches: 4
  log_every_n_steps: 100


Callbacks:

  LearningRateMonitor:
    logging_interval: step


Profiler:
  PyTorchProfiler:

