defaults:
  - _self_
  - dataset: COCO2017
  - trainer: default

trainer:
  Trainer:
    overfit_batches: 10

batch_size: 8
num_workers: 2
ckpt_path: 


model:
  model:
    coeff: 0

  loss:
    fore_th: 0.5
    back_th: 0.4
    alpha: 0.25
    gamma: 1.5
    beta: 0.1
    fore_mean: True
    reg_weight:
    average: True

  nms:
    iou_th: 0.5
    max_det: 400

  optimizer:
    lr: 0.0001


log:
  name: exp0-run0
  project: COCO_EfficientDet
  save_dir: ./log
  artifact_type: find_lr
  artifact_name: experiment_0
  artifact_description: lr=0.0001 | scheduler=ReduceLROnPlateau | monitor=AP
  artifact_save_files:
    trainer: config/trainer/default.yaml