# trainer:
#   Trainer:
#     overfit_batches: 20

defaults:
  - _self_
  - trainer: default
  - dataset: COCO2017-local


batch_size: 8
num_workers: 2
use_background_class: false
# ckpt_path: ./log/COCO_EfficientDet/0w4ghln0/checkpoints/epoch=1-step=7394.ckpt
load_ckpt_weight: ./log/COCO_EfficientDet/nd4l5k2x/checkpoints/epoch=33-step=125698.ckpt

trainer:
  Task:
    pl_module: Laion400m_EfficientDet
  Trainer:
    accumulate_grad_batches: 2
    limit_train_batches: 0.1

model:
  model:
    coeff: 0

  loss:
    fore_th: 0.5
    back_th: 0.4
    alpha: 0.25
    gamma: 1.5
    beta: 0.1
    fore_mean: True
    reg_weight:
    average: True

  nms:
    iou_th: 0.5
    max_det: 400

  optimizer:
    lr: 0.0001


log:
  name: local-run0
  project: COCO_EfficientDet
  save_dir: ./log
  artifact_type: find_lr
  artifact_name: experiment_0
  artifact_description: lr=0.0002 | scheduler=ReduceLROnPlateau | monitor=AP
  artifact_save_files:
    trainer: config/trainer/default.yaml
