defaults:
  - dataset: VisualGenome
  - trainer: default
  - _self_

freeze_backbone: false
use_background_class: false
batch_size: 12
num_workers: 2
# ckpt_path: tmp.ckpt
load_ckpt_weight: ./log/COCO_EfficientDet/1rl3pd0c/checkpoints/epoch=68-step=295182.ckpt

trainer:
  Task:
    pl_module: VisGenome_FuseDet

  Trainer:
    accumulate_grad_batches: 1
    # strategy: ddp
    sync_batchnorm: true
    precision: 16
    # overfit_batches: 36
    limit_train_batches: 1.0

model:
  model:
    coeff: 0

  loss:
    fore_th: 0.5
    back_th: 0.4
    alpha: 0.25
    gamma: 1.5
    beta: 0.1
    fore_mean: True
    reg_weight:
    average: True

  nms:
    iou_th: 0.5
    max_det: 20

  optimizer:
    lr: 0.0001


log:
  name: visual-genome-fusedet-convnext
  project: COCO_EfficientDet
  save_dir: ./log
  artifact_type: find_lr
  artifact_name: visual-genome-fusedet-convnext
  artifact_description: lr=0.0001 | scheduler=ReduceLROnPlateau | monitor=AP | ConvNeXt-Laion2B
  artifact_save_files:
    trainer: config/trainer/default.yaml