defaults:
  - dataset: VisualGenome
  - trainer: default
  - _self_

freeze_backbone: true
use_background_class: false
batch_size: 16
num_workers: 2
ckpt_path: 

trainer:
  Task:
    pl_module: VisGenome_EfficientDet

  Trainer:
    accumulate_grad_batches: 1
    # strategy: ddp
    sync_batchnorm: true
    overfit_batches: 36

model:
  model:
    coeff: 0

  loss:
    fore_th: 0.5
    back_th: 0.4
    alpha: 0.25
    gamma: 1.5
    beta: 0.1
    fore_mean: True
    reg_weight:
    average: True

  nms:
    iou_th: 0.5
    max_det: 400

  optimizer:
    lr: 0.0001


log:
  name: laion-convnext
  project: COCO_EfficientDet
  save_dir: ./log
  artifact_type: find_lr
  artifact_name: laion-convnext
  artifact_description: lr=0.0001 | scheduler=ReduceLROnPlateau | monitor=AP | ConvNeXt-Laion2B
  artifact_save_files:
    trainer: config/trainer/default.yaml