train:
  root: /home/ron_zhu/mscoco/train2017
  annFile: /home/ron_zhu/mscoco/annotations/instances_train2017.json

val:
  root: /home/ron_zhu/mscoco/val2017
  annFile: /home/ron_zhu/mscoco/annotations/instances_val2017.json

test:
  root: /home/ron_zhu/mscoco/val2017

dataset_stat:
  - [0.485, 0.456, 0.406]   # mean
  - [0.229, 0.224, 0.225]   # std
