train:
  root: /home/ron_zhu/laion-400m/train_data
  annFile: 

val:
  root: /home/ron_zhu/laion-400m/val_data
  annFile: 

test:
  root: 

dataset_stat:
  - [0.485, 0.456, 0.406]   # mean
  - [0.229, 0.224, 0.225]   # std
